### ISSUE TITLE
1º inga.js - Sumério Cervejas Especiais

### ISSUE THREAD

**Issue by wwwflorencio** [inga-js/meetups#2]
# 1º inga.js
## Quinta, 09 de agosto de 2018 18:30
------

Eae, primeiro role. Vamos trabalhar com talks de 20 minutos o/

Inscrições em:
https://www.meetup.com/pt-BR/developerparana/events/253321884/

Nossa parceria:
https://www.facebook.com/sumeriobeer/

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1:  serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

Para submeter palestras comente nessa issue seguindo o modelo da issue #1

**Comment by EloPo** [comment]
## P5.js - um jeito JavaScript de fazer um jogo

#### Nome
Eloisa Potrich

#### Twitter
@ello_po

#### Grau da palestra
- [X] Iniciante
- [ ] Intermediário
- [ ] Avançado

O P5.js é uma biblioteca JavaScript que começa com o objetivo original de Processing, para tornar a codificação acessível para artistas, designers, para o desenvolvimento, principalmente de um jogo.
Irei mostrar como iniciar um jogo bem simples, desde o começo até o fim

**Comment by wwwflorencio** [comment]
## Criando seus próprios módulos NPM

#### Nome
Marcos Florencio

#### Twitter
@eptaccio

#### Grau da palestra
- [ ] Iniciante
- [X] Intermediário
- [ ] Avançado

Vou compartilhar minha experiência criando e reutilizando pacotes npm em projetos grandes e múltiplos serviços além de um pequeno guia de como iniciar.

**Comment by emanoelvso** [comment]
# Entendendo Promises e async/await

**Nome**
Emanoel Oliveira

**Twitter**
@EmanoelOliveria

**Grau da palestra**

- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado

Vou exemplificar a utilização de ambas as tecnologias assíncronas, desde a parte teórica até à pratica, abordando as vantagens em utilizar cada uma.

Assim como apresentar as principais diferenças entre callback vs Promise e Promise vs async/await

**Comment by ferfabricio** [comment]
## Higher-Order Components (HOC)

#### Nome
Fernando Fabricio dos Santos

#### Grau da palestra
- [ ] Iniciante
- [ ] Intermediário
- [x] Avançado

#### Abstract
Higher-Order Components não são parte de nenhum framework e sim um padrão de desenvolvimento.
A motivação da palestra é mostrar como utilizar, casos onde possam ser utilizados e casos onde não são necessários.

Ps: Os exemplos serão em React! (não chora!)

**Comment by SauloNunes** [comment]
## Iniciando com React Native

#### Nome
Saulo nunes

#### Grau da palestra
- [x ] Iniciante
- [ ] Intermediário
- [ ] Avançado

#### Abstract
O Objetivo é montar um ambiente de desenvolvimento com Node, React Native e suas Dependências. mostrando um exemplo pratico com deploy em um Dispositivo Android.
