### ISSUE TITLE
3º inga.js - Sumério

### ISSUE THREAD

**Issue by wwwflorencio** [inga-js/meetups#3]
# 3º Ingá.js
Meetup para discussão do universo javascript e node

## Quinta, 07 de fevereiro de 2019 18:30

Talks de 20 minutos o/

Inscrições em:
https://www.meetup.com/developerparana/events/258333344

Nossa parceria:
https://www.facebook.com/sumeriobeer/

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1:  serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

Para submeter palestras comente nessa issue seguindo o modelo da issue #1

**Comment by iamgbayer** [comment]
## Um pouco mais sobre Web Offline e Service Workers

#### Nome
Guilherme Bayer

#### Twitter
@guuibayer

#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado

Veremos um pouco sobre alguns recursos que estão disponíveis com a utilização de Service Workers, formas de armazenamento no cliente e como isso contribui para uma experiência impar do usuário nesse cenário.

**Comment by andrevandal** [comment]
## VueJs: Imagens com LazyLoad através da API IntersectionObserver

#### Nome
André Van Dal

#### Twitter
@derevandal

#### Grau da palestra
* [ x ]  Iniciante
* [    ]  Intermediário
* [    ]  Avançado

#### Resumo
Criaremos um componente com VueJs para carregar images dinamicamente apenas quando houver a necessidade de mostrá-las através da API IntersectionObserver

**Comment by ghost** [comment]
### Nginx: Criando proxy reverso para aplicacoes que estao rodando em docker

Nome
**Gabriel De Moura Dutra** 

Twitter
**@g_mdutra**

Grau da palestra
[ x ] Iniciante
[ ] Intermediário
[ ] Avançado

Resumo
Criaremos um proxy reverso com o nginx para aplicacoes que estao rodando em docker e iremos usar o prometheus para monitorar as requisicoes que o nginx esta recebendo.

**Comment by frontendwizard** [comment]
# React Hooks - A nova API do React

**Nome**
Juliano Rafael

**Twitter**
frontendwizard

**Grau da palestra**
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado

**Resumo**
Vamos conversar sobre a nova API do React, os hooks, discutir quando é interessante refatorar seu código e porque ela é tão interessante para o ecossistema React e as aplicações no front end.

**Comment by vinicius91** [comment]
# Schematics ao resgate: Automação para recuperar a diversão

### Nome
Vinicius Rodrigues

### Twitter
@_viniro

### Grau da palestra

- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado

### Resumo
A medida que as aplicações vão crescendo, o boilerplate do nosso código também cresce, e em paralelo cresce a dificuldade de fazer com que os padrões de projetos adotados  sejam mantidos, principalmente em equipes grades e distribuídas. Com esses problemas em mente, existe uma ferramenta dentro do AngularDevKit que vem ganhando destaque, os Schematics. Meu objetivo é apresentar essa ferramenta, alguns exemplos, e uma maneira de evitar as algumas partes chatas de escrever código.

**Comment by wwwflorencio** [comment]
C4P Fechado, no momento ganharam via votação as talks:

Um pouco mais sobre Web Offline e Service Workers (13 :+1: )
Guilherme Bayer @guuibayer 

VueJs: Imagens com LazyLoad através da API IntersectionObserver (11 :+1: )
André Van Dal @derevandal 

Schematics ao resgate: Automação para recuperar a diversão (4 :+1: )
Vinicius Rodrigues @vinicius91 

As demais talks serão reaproveitas em outro role, obrigado a todos <3

Teremos 3 palestras técnicas no role e uma palestra com uma Psicologa falando sobre trabalho e depressão.
